export { default as Banner } from './Banner'
export { default as Categories } from './Categories'
export { default as Exclusive } from './Exclusive'
export { default as HowToBuy } from './HowToBuy'
export { default as NewArrival } from './NewArrival'
export { default as TopRated } from './TopRated'
